# Generated by Django 4.1.2 on 2022-10-06 17:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='cost',
            field=models.IntegerField(default=100, verbose_name='стоимость месяца подписки в рублях'),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='payment_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True, verbose_name='Идентификатор платежа'),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='stripe_payment_id',
            field=models.CharField(blank=True, default='', editable=False, max_length=100, verbose_name='Ид. платежа stripe'),
        ),
    ]
