# Generated by Django 4.1.2 on 2022-10-06 17:32

import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('planes', 'Subscribe')
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])
    

class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0002_subscribe_cost_subscribe_payment_id_and_more'),
    ]

    operations = [
        migrations.RunPython(gen_uuid)
    ]
