# Generated by Django 4.1.2 on 2022-10-06 17:32

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0003_auto_20221006_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='payment_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификатор платежа'),
        ),
    ]
