# Generated by Django 4.1.2 on 2022-10-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0006_alter_subscribe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='calories',
            field=models.PositiveIntegerField(default=0, verbose_name='Калории'),
        ),
    ]
