# Generated by Django 4.1.2 on 2022-10-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0007_subscribe_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='menutype',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Картинка'),
        ),
    ]
