# Generated by Django 4.1.2 on 2022-10-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0009_alter_dish_calories_alter_dish_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='calories',
            field=models.PositiveIntegerField(default=0, verbose_name='Калорийность'),
        ),
    ]
