# Generated by Django 4.1.2 on 2022-10-09 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0011_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100, verbose_name='источник перехода')),
                ('medium', models.CharField(max_length=100, verbose_name='тип трафика')),
                ('campaign', models.CharField(max_length=100, verbose_name='название компании')),
                ('content', models.CharField(default=None, max_length=100, null=True, verbose_name='информация о содержимом')),
                ('term', models.CharField(default=None, max_length=100, null=True, verbose_name='ключевое слово')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
            ],
        ),
        migrations.AddField(
            model_name='subscribe',
            name='utm',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscribes', to='planes.utm', verbose_name='UTM-метка'),
        ),
    ]
