# Generated by Django 4.1.2 on 2022-10-09 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0012_alter_dishingredient_dish'),
        ('planes', '0012_utm_subscribe_utm'),
    ]

    operations = [
    ]
