# Generated by Django 4.1.2 on 2022-10-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0015_alter_allergy_options_alter_dish_options_dishesofday'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishesofday',
            name='menu_type',
            field=models.CharField(blank=True, max_length=30, verbose_name='Тип меню'),
        ),
    ]
